version: '3.3'



services:
  mysql_service:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotipo
    ports:
      - "33060:3306"
    volumes:
      - ./data/db.sql:/docker-entrypoint-initdb.d/setup.sql

  redis_service:
    image: redis

  radius:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - mysql_service
      - redis_service
    ports:
      - "0.0.0.0:1812:1812/udp"
      - "0.0.0.0:1813:1813/udp"
    command:  ["./wait-for-it.sh", "mysql_service:3036","--","./entrypoint.sh"]